//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version Beta 1.2
//
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Beta Version
//
package com.contactpoint.model.client.prv;

import java.util.Hashtable;
import java.util.Vector;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
public class VectorPRVResult extends Vector<PRVResult> implements KvmSerializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = -4668207067933954494L;

	public VectorPRVResult(){}
    
    public VectorPRVResult(SoapObject soapObject)
    {
        if (soapObject != null){
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0<size;i0++){
                Object obj = soapObject.getProperty(i0);
                if (obj.getClass().equals(SoapObject.class)){
                    SoapObject j0 =(SoapObject) soapObject.getProperty(i0);
                    PRVResult j1= new PRVResult(j0);
                    add(j1);
                }
            }
        }
        }
    @Override
    public Object getProperty(int arg0) {
        return this.get(arg0);
    }

    @Override
    public int getPropertyCount() {
        return this.size();
    }

    @Override
    public void getPropertyInfo(int arg0, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo arg2) {
        arg2.name = "PRVResult";
        arg2.type = PRVResult.class;
    }

    @Override
    public void setProperty(int arg0, Object arg1) {
        this.add((PRVResult)arg1);
    }

}
