//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version Beta 1.2
//
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Beta Version
//
package com.contactpoint.model.client.authentication;

import java.util.Hashtable;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class AuthenticationToken implements KvmSerializable {

	public final static String NAMESPACE = "http://TMSConsultant.Model/2013/Authentication";
	public final static String MM_NAMESPACE = "http://schemas.datacontract.org/2004/07/TollTransitions.API.DataContracts";
	public String machineKey;
	public String deviceID;
	public String username;
	public String group;
	private boolean isMM;

	public AuthenticationToken(){}

	public AuthenticationToken(SoapObject soapObject){

		if (soapObject.hasProperty("MachineKey"))
		{
			Object obj = soapObject.getProperty("MachineKey");
			if (obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j2 =(SoapPrimitive) soapObject.getProperty("MachineKey");
				machineKey = j2.toString();
			}
		}
		if (soapObject.hasProperty("DeviceID"))
		{
			Object obj = soapObject.getProperty("DeviceID");
			if (obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j3 =(SoapPrimitive) soapObject.getProperty("DeviceID");
				deviceID = j3.toString();
			}
		}
		if (soapObject.hasProperty("Username"))
		{
			Object obj = soapObject.getProperty("Username");
			if (obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j4 =(SoapPrimitive) soapObject.getProperty("Username");
				username = j4.toString();
			}
		}
		if (soapObject.hasProperty("Group"))
		{
			Object obj = soapObject.getProperty("Group");
			if (obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j5 =(SoapPrimitive) soapObject.getProperty("Group");
				group = j5.toString();
			}
		}
	}
	@Override
	public Object getProperty(int arg0) {
		switch(arg0){
		case 0:
			return machineKey;
		case 1:
			return deviceID;
		case 2:
			return username;
		case 3:
			return group;
		}
		return null;
	}
	@Override
	public int getPropertyCount() {
		return 4;
	}
	@Override
	public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		if (this.isMM) {
			info.namespace = MM_NAMESPACE;
		} else {
			info.namespace = NAMESPACE;
		}
		switch(index){
		case 0:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "MachineKey";
			break;
		case 1:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "DeviceID";
			break;
		case 2:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = this.isMM ? "UserName" : "Username";
			break;
		case 3:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "Group";
			break;
		}
	}
	@Override
	public void setProperty(int index, Object value) {
		switch(index){
		case 0:
			machineKey = value.toString() ;
			break;
		case 1:
			deviceID = value.toString() ;
			break;
		case 2:
			username = value.toString() ;
			break;
		case 3:
			group = value.toString() ;
			break;
		}
	}
	
	public void setIsMM(boolean isMM) {
		this.isMM = isMM;
	}
	
	public boolean isMM() {
		return this.isMM;
	}
}
