//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version Beta 1.2
//
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Beta Version
//
package com.contactpoint.model.client.authentication;

import java.util.Hashtable;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Login implements KvmSerializable {

	public String NAMESPACE = "http://TMSConsultant.Model/2013/Authentication";
	public String username;
	public String password;

	public Login(){}

	public Login(SoapObject soapObject){

		if (soapObject.hasProperty("Username"))
		{
			Object obj = soapObject.getProperty("Username");
			if (obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j6 =(SoapPrimitive) soapObject.getProperty("Username");
				username = j6.toString();
			}
		}
		if (soapObject.hasProperty("Password"))
		{
			Object obj = soapObject.getProperty("Password");
			if (obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j7 =(SoapPrimitive) soapObject.getProperty("Password");
				password = j7.toString();
			}
		}
	}
	@Override
	public Object getProperty(int arg0) {
		switch(arg0){
		case 0:
			return username;
		case 1:
			return password;
		}
		return null;
	}
	@Override
	public int getPropertyCount() {
		return 2;
	}
	@Override
	public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		info.namespace = NAMESPACE;
		switch(index){
		case 0:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "Username";
			break;
		case 1:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "Password";
			break;
		}
	}
	@Override
	public void setProperty(int index, Object value) {
		switch(index){
		case 0:
			username = value.toString() ;
			break;
		case 1:
			password = value.toString() ;
			break;
		}
	}
}
