//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version Beta 1.2
//
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Beta Version
//
package com.contactpoint.model.client.ci;

import java.io.Serializable;
import java.util.Hashtable;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class Name implements KvmSerializable, Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4226938448228841391L;
	public String NAMESPACE = "http://TMSConsultant.Model/2013/ProcessCI";
	public String title;
	public String firstName;
	public String middleName;
	public String lastName;

	public Name(){}

	public Name(SoapObject soapObject){

		if (soapObject.hasProperty("Title"))
		{
			Object obj = soapObject.getProperty("Title");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j37 =(SoapPrimitive) soapObject.getProperty("Title");
				title = j37.toString();
			}
		}
		if (soapObject.hasProperty("FirstName"))
		{
			Object obj = soapObject.getProperty("FirstName");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j38 =(SoapPrimitive) soapObject.getProperty("FirstName");
				firstName = j38.toString();
			}
		}
		if (soapObject.hasProperty("MiddleName"))
		{
			Object obj = soapObject.getProperty("MiddleName");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j39 =(SoapPrimitive) soapObject.getProperty("MiddleName");
				middleName = j39.toString();
			}
		}
		if (soapObject.hasProperty("LastName"))
		{
			Object obj = soapObject.getProperty("LastName");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
				SoapPrimitive j40 =(SoapPrimitive) soapObject.getProperty("LastName");
				lastName = j40.toString();
			}
		}
	}
	@Override
	public Object getProperty(int arg0) {
		switch(arg0){
		case 0:
			return title;
		case 1:
			return firstName;
		case 2:
			return middleName;
		case 3:
			return lastName;
		}
		return null;
	}
	@Override
	public int getPropertyCount() {
		return 4;
	}
	@Override
	public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
		switch(index){
		case 0:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "Title";
			break;
		case 1:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "FirstName";
			break;
		case 2:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "MiddleName";
			break;
		case 3:
			info.type = PropertyInfo.STRING_CLASS;
			info.name = "LastName";
			break;
		}
	}
	@Override
	public void setProperty(int index, Object value) {
		switch(index){
		case 0:
			title = value.toString() ;
			break;
		case 1:
			firstName = value.toString() ;
			break;
		case 2:
			middleName = value.toString() ;
			break;
		case 3:
			lastName = value.toString() ;
			break;
		}
	}
	
	@Override
	public String toString() {
		String fullName = "";
		if (title != null && title.length() != 0) 	  fullName += title + " ";
		if (firstName != null && firstName.length() != 0)  fullName += firstName + " ";
		if (middleName != null && middleName.length() != 0) fullName += middleName + " ";
		if (lastName != null && lastName.length() != 0)   fullName += lastName;
		return fullName;
	}
}
